### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by ReubenMcG** [matsengrp/phippery#182]
https://matsengrp.github.io/phippery/alignments-pipeline.html specifies 

"The fastq files pointed to by the sample table described above are assumed to have uniform (trimmed) read lengths. During alignment, this is enforced by reads being trimmed on the 3’ end to match the length specified by the **--oligo_tile_length** parameter."

But in "Parameters" section --peptide_tile_length is specified.

Are these the same? 

Also if my library has varying  tile lengths how would I overcome this?

**Comment by jgallowa07** [comment]
Sorry for the late reply @ReubenMcG.

> But in "Parameters" section --peptide_tile_length is specified.
> 
> Are these the same?

Thanks for pointing this out, I've fixed this in #185 

> Also if my library has varying tile lengths how would I overcome this?

This is outside the typical sliding window approach of designing peptide libraries, and thus we do not currently support variable length tiles. This is because our pipeline alignment step defines a "seed" length (i.e. length of peptide encoding oligo sequence) for bowtie such that a given read must not exceed `--n_mismatches` from the 5' end (left-most) of the read through the expected "seed" (peptide-encoding oligo) length. I can imagine for variable length peptides you would need to use bowtie's `-v` mode. See the [updated alignment approach documentation](https://matsengrp.github.io/phippery/examples.html#alignment-approach) for more details on how exactly we perform alignment, and how you might modify it to fit you needs. 

I'm closing this for now as the documentation should be clear on the requirements and scope of this pipeline. While I'm too busy to advice on potential modifications, If you happen to figure it out and would like to contribute I'll happily review a PR.
